name: Build

on: push

jobs:
  prebuild-lib:
    name: Prebuild lib

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Alsa lib
        if: "runner.os == 'Linux'"
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libpulse-dev

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build-binaries

  prebuild-lib-armv7:
    name: Prebuild lib ARMv7
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build for armv7
      run: ./scripts/build_for_arch.sh

